const airlines=[
{name:"Air Algérie",code:"AH"},
{name:"Air France",code:"AF"},
{name:"Aegean Airlines",code:"A3"},
{name:"AeroMexico",code:"AM"},
{name:"Aer Lingus",code:"EI"},
{name:"Aeroflot",code:"SU"},
{name:"Air Canada",code:"AC"},
{name:"Air China",code:"CA"},
{name:"Air Europa",code:"UX"},
{name:"Air India",code:"AI"},
{name:"Air New Zealand",code:"NZ"},
{name:"Air Portugal TAP",code:"TP"},
{name:"Air Serbia",code:"JU"},
{name:"Alitalia",code:"AZ"},
{name:"American Airlines",code:"AA"},
{name:"ANA All Nippon Airways",code:"NH"},
{name:"Asiana Airlines",code:"OZ"},
{name:"Austrian Airlines",code:"OS"},
{name:"Azerbaijan Airlines",code:"J2"},
{name:"British Airways",code:"BA"},
{name:"Brussels Airlines",code:"SN"},
{name:"Bulgaria Air",code:"FB"},
{name:"Cathay Pacific",code:"CX"},
{name:"China Airlines",code:"CI"},
{name:"China Eastern Airlines",code:"MU"},
{name:"China Southern Airlines",code:"CZ"},
{name:"Copa Airlines",code:"CM"},
{name:"Croatia Airlines",code:"OU"},
{name:"Czech Airlines",code:"OK"},
{name:"Delta Air Lines",code:"DL"},
{name:"EgyptAir",code:"MS"},
{name:"Emirates",code:"EK"},
{name:"Ethiopian Airlines",code:"ET"},
{name:"Etihad Airways",code:"EY"},
{name:"Eurowings",code:"EW"},
{name:"Finnair",code:"AY"},
{name:"FlyDubai",code:"FZ"},
{name:"Garuda Indonesia",code:"GA"},
{name:"Gulf Air",code:"GF"},
{name:"Hainan Airlines",code:"HU"},
{name:"Iberia",code:"IB"},
{name:"Icelandair",code:"FI"},
{name:"ITA Airways",code:"AZ"},
{name:"Japan Airlines",code:"JL"},
{name:"JetBlue",code:"B6"},
{name:"Kenya Airways",code:"KQ"},
{name:"KLM Royal Dutch Airlines",code:"KL"},
{name:"Korean Air",code:"KE"},
{name:"Kuwait Airways",code:"KU"},
{name:"LATAM Airlines",code:"LA"},
{name:"LOT Polish Airlines",code:"LO"},
{name:"Lufthansa",code:"LH"},
{name:"Malaysia Airlines",code:"MH"},
{name:"Middle East Airlines",code:"ME"},
{name:"Norwegian Air",code:"DY"},
{name:"Oman Air",code:"WY"},
{name:"Pegasus Airlines",code:"PC"},
{name:"Philippine Airlines",code:"PR"},
{name:"Qantas",code:"QF"},
{name:"Qatar Airways",code:"QR"},
{name:"Royal Air Maroc",code:"AT"},
{name:"Royal Jordanian",code:"RJ"},
{name:"Ryanair",code:"FR"},
{name:"Saudia",code:"SV"},
{name:"Singapore Airlines",code:"SQ"},
{name:"South African Airways",code:"SA"},
{name:"Southwest Airlines",code:"WN"},
{name:"SriLankan Airlines",code:"UL"},
{name:"Swiss International Air Lines",code:"LX"},
{name:"Tunisair",code:"TU"},
{name:"Turkish Airlines",code:"TK"},
{name:"Ukraine International Airlines",code:"PS"},
{name:"United Airlines",code:"UA"},
{name:"Vietnam Airlines",code:"VN"},
{name:"Virgin Atlantic",code:"VS"},
{name:"Vueling",code:"VY"},
{name:"Wizz Air",code:"W6"},
{name:"Qatar Executive",code:"QE"},
{name:"Royal Air Philippines",code:"RW"},
{name:"Saudia Cargo",code:"SV"},
{name:"Transavia",code:"HV"},
{name:"WestJet",code:"WS"}
];