const airports=[
{name:"Alger Houari Boumediene",city:"Alger",country:"Algérie",code:"ALG"},
{name:"Oran Ahmed Ben Bella",city:"Oran",country:"Algérie",code:"ORN"},
{name:"Constantine Mohamed Boudiaf",city:"Constantine",country:"Algérie",code:"CZL"},
{name:"Sétif 8 Mai 1945",city:"Sétif",country:"Algérie",code:"QSF"},
{name:"Paris Charles de Gaulle",city:"Paris",country:"France",code:"CDG"},
{name:"Paris Orly",city:"Paris",country:"France",code:"ORY"},
{name:"Lyon Saint Exupéry",city:"Lyon",country:"France",code:"LYS"},
{name:"Marseille Provence",city:"Marseille",country:"France",code:"MRS"},
{name:"Nice Côte d'Azur",city:"Nice",country:"France",code:"NCE"},
{name:"London Heathrow",city:"London",country:"United Kingdom",code:"LHR"},
{name:"London Gatwick",city:"London",country:"United Kingdom",code:"LGW"},
{name:"Manchester Airport",city:"Manchester",country:"United Kingdom",code:"MAN"},
{name:"Dubai International",city:"Dubai",country:"UAE",code:"DXB"},
{name:"Abu Dhabi International",city:"Abu Dhabi",country:"UAE",code:"AUH"},
{name:"Doha Hamad International",city:"Doha",country:"Qatar",code:"DOH"},
{name:"Riyadh King Khalid International",city:"Riyadh",country:"Saudi Arabia",code:"RUH"},
{name:"Jeddah King Abdulaziz International",city:"Jeddah",country:"Saudi Arabia",code:"JED"},
{name:"Istanbul Airport",city:"Istanbul",country:"Turkey",code:"IST"},
{name:"Sabiha Gökçen Airport",city:"Istanbul",country:"Turkey",code:"SAW"},
{name:"Rome Fiumicino",city:"Rome",country:"Italy",code:"FCO"},
{name:"Milan Malpensa",city:"Milan",country:"Italy",code:"MXP"},
{name:"Madrid Barajas",city:"Madrid",country:"Spain",code:"MAD"},
{name:"Barcelona El Prat",city:"Barcelona",country:"Spain",code:"BCN"},
{name:"Lisbon Humberto Delgado",city:"Lisbon",country:"Portugal",code:"LIS"},
{name:"Amsterdam Schiphol",city:"Amsterdam",country:"Netherlands",code:"AMS"},
{name:"Brussels Airport",city:"Brussels",country:"Belgium",code:"BRU"},
{name:"Frankfurt Airport",city:"Frankfurt",country:"Germany",code:"FRA"},
{name:"Munich Airport",city:"Munich",country:"Germany",code:"MUC"},
{name:"Vienna International",city:"Vienna",country:"Austria",code:"VIE"},
{name:"Zurich Airport",city:"Zurich",country:"Switzerland",code:"ZRH"},
{name:"Athens International",city:"Athens",country:"Greece",code:"ATH"},
{name:"Cairo International",city:"Cairo",country:"Egypt",code:"CAI"},
{name:"Casablanca Mohammed V",city:"Casablanca",country:"Morocco",code:"CMN"},
{name:"Tunis Carthage",city:"Tunis",country:"Tunisia",code:"TUN"},
{name:"Istanbul Airport",city:"Istanbul",country:"Turkey",code:"IST"},
{name:"Beijing Capital International",city:"Beijing",country:"China",code:"PEK"},
{name:"Shanghai Pudong International",city:"Shanghai",country:"China",code:"PVG"},
{name:"Tokyo Haneda",city:"Tokyo",country:"Japan",code:"HND"},
{name:"Tokyo Narita",city:"Tokyo",country:"Japan",code:"NRT"},
{name:"Seoul Incheon",city:"Seoul",country:"South Korea",code:"ICN"},
{name:"Singapore Changi",city:"Singapore",country:"Singapore",code:"SIN"},
{name:"Bangkok Suvarnabhumi",city:"Bangkok",country:"Thailand",code:"BKK"},
{name:"New Delhi Indira Gandhi",city:"New Delhi",country:"India",code:"DEL"},
{name:"Mumbai Chhatrapati Shivaji",city:"Mumbai",country:"India",code:"BOM"},
{name:"New York JFK",city:"New York",country:"USA",code:"JFK"},
{name:"New York Newark",city:"New York",country:"USA",code:"EWR"},
{name:"Los Angeles International",city:"Los Angeles",country:"USA",code:"LAX"},
{name:"Miami International",city:"Miami",country:"USA",code:"MIA"},
{name:"Toronto Pearson",city:"Toronto",country:"Canada",code:"YYZ"},
{name:"Montreal Trudeau",city:"Montreal",country:"Canada",code:"YUL"},
{name:"São Paulo Guarulhos",city:"São Paulo",country:"Brazil",code:"GRU"},
{name:"Mexico City International",city:"Mexico City",country:"Mexico",code:"MEX"},
{name:"Sydney Kingsford Smith",city:"Sydney",country:"Australia",code:"SYD"},
{name:"Melbourne Airport",city:"Melbourne",country:"Australia",code:"MEL"}
];